---
- hosts: localhost
  connection: local

  vars_files:
    - "vars/fromTerraform.yml"
    #- "vars/creds.json"


  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Modify SE group
      avi_serviceenginegroup:
        cloud_ref: "/api/cloud/?name={{ avi_cloud.name }}"
        avi_api_update_method: put
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        ha_mode: "{{ item.ha_mode }}"
        min_scaleout_per_vs: "{{ item.min_scaleout_per_vs }}"
        buffer_se: "{{ item.buffer_se }}"
        extra_shared_config_memory: "{{ item.extra_shared_config_memory }}"
        vcenter_folder: "{{ item.vcenter_folder }}"
        vcpus_per_se: "{{ item.vcpus_per_se }}"
        memory_per_se: "{{ item.memory_per_se }}"
        disk_per_se: "{{ item.disk_per_se }}"

      when: serviceEngineGroup is defined
      loop: "{{ serviceEngineGroup }}"
      loop_control:
        label: "Modifying SE group called {{ item.name }}"
